---
title           : "Variation in male greater sage grouse abundance at lek sites in Grasslands National Park, Saskatchewan"
date            : 2022-09-26

author: 
  - name        : Katlin McCallum
    affiliation : 1

affiliation:
  - id          : 1
    institution : Department of Biology, University of Regina

output: pdf_document
---



library(groundhog) 
groundhog.library(tidyverse, date = "2022-09-15") groundhog.library(ggplot2, date = "2022-09-15")

Format is for Ecology Letters

geometry: margin=1in

head-includes: -

\\usepackage{setspace} \\doublespacing \\usepackage{lineno} \\linenumbers

output: pdf_document

csl: <https://raw.githubusercontent.com/citation-style-language/styles/6152ccea8b7d7a472910d36524d1bf3557a83bfc/ecology-letters.csl>

## bibliography: references.bib

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Title:** Variation in greater sage grouse abundance at lek sites in Grasslands National Park, Saskatchewan

Katlin McCallum^1^

1.  Department of Biology, University of Regina

# Abstract

Grasslands National Park in southern Saskatchewan has a population of greater sage grouse. Each spring, the male greater sage grouse congregate in groups at known locations to lek. These lek sites were monitored from 2007-2020 and the abundance of male birds was counted at each site. I am graphically illustrating the abundance trends over the years for each lek site.

# Introduction

# Methods

Grasslands National Park staff observed lek sites during the breeding season from 2005-2020. The maximum number of male birds at a lek site at one time was termed peak male attendance and this was recorded for each lek site. Using the ggplot2 package in R, I am graphically representing the variation in abundance between lek sites over the 15 years of observations.

# Results

# Discussion

# References

# Tables

# Figure Captions

# Figures

# Appendices
