---
title           : "Pre-Registration for Greater Sage Grouse Abundance"
shorttitle      : "Preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Katlin McCallum
    affiliation : 1

affiliation:
  - id          : 1
    institution : University of Regina

output: pdf_document
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->

## Data collection

<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

**Yes**, we already collected the data.

## Hypothesis

<!-- What's the main question being asked or hypothesis being tested in this study? -->

> Does male greater sage grouse abundance vary between lek sites?

## Dependent variable

<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> Greater sage grouse abundance is the key dependent variable and it was measured by counting the maximum number of male grouse visiting the lek site.

## Analyses

<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> To examine the research question, the abundance of greater sage grouse at the peak time will be plotted on a graph against the lek site. This will visually illustrate if there is variability in the number of grouse visiting the lek sites.

## Outliers and exclusions

<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> Outliers will not be considered in this study. All observations of a confirmed male grouse at a lek site will be included.

## Sample size

<!-- How many observations will be collected or what will determine sample size? No need to justify decision, but be precise about _exactly_ how the number will be determined. -->

> The grouse will determine the sample size.

## Other

<!-- Anything else you would like to pre-register? (e.g., secondary analyses, variables collected for exploratory purposes, unusual analyses planned?) -->

> Grouse can be hard to sex during field observations. If the sex is unknown, that bird will be excluded from the analysis.

## Study type

Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

-   Class project or assignment

# References

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
